#url: https://y7kim.github.io
#baseurl: /anno-fund/

# Site settings
title: Open Annotation Fund
email: fund@hypothes.is
description: "Funding grants for Open Annotation: the web-based, implementation
  of an interoperable, standards-based annotation paradigm that promises to
  become a new layer over human knowledge"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: BB1E2D
  secondary: D33744
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Phil Desenne
#  pic: 1
  position: Annotation Lead, HarvardX / edX
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #

- name: Rob Sanderson
#  pic: 3
  position: Co-Chair, Open Annotation Community Group, Stanford University
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #

- name: Doug Schepers
#  pic: 2
  position: Developer Relations, W3C
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #

- name: Nick Stenning
#  pic: 3
  position: Lead Developer, Annotator, Hypothes.is
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/hypothes_is
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/hypothesis

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
